version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-jwt
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: jwt_demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: jwt-node-app
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm start

volumes:
  pgdata:
